// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO9avWIpERAXpqlCNk01foWfgzu1S76Y4',
    appId: '1:931922614420:android:024a3974c96cf97699fc81',
    messagingSenderId: '931922614420',
    projectId: 'lettutor-3896c',
    storageBucket: 'lettutor-3896c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWSEiolatU_3W47IlhxsY_JmcKJ-zkH0g',
    appId: '1:931922614420:ios:95441ff803bd0eb899fc81',
    messagingSenderId: '931922614420',
    projectId: 'lettutor-3896c',
    storageBucket: 'lettutor-3896c.appspot.com',
    iosClientId: '931922614420-6inh9r9e5clnj6lkeikt0r9g34hh1ukp.apps.googleusercontent.com',
    iosBundleId: 'let',
  );
}
